# Generated by Django 5.2.17 on 2026-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_for_order']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['place_for_order']},
        ),
        migrations.AddField(
            model_name='image',
            name='image_for_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='place_for_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
