# Generated by Django 5.2.17 on 2026-09-18 17:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='editor',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
