# Generated by Django 5.2.17 on 2026-09-18 17:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='editor',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
    ]
