# Generated by Django 5.2.17 on 2026-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_place_editor_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_for_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_for_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
