# Generated by Django 5.2.17 on 2026-09-21 18:11

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_order']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['place_order']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_for_order',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_for_order',
        ),
        migrations.AddField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='place_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
