# Generated by Django 5.2.17 on 2026-09-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['place']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_order',
        ),
    ]
