# Generated by Django 5.2.17 on 2026-09-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_image_options_remove_image_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_order'], 'verbose_name': 'фото', 'verbose_name_plural': 'фото'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['order'], 'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_order',
            new_name='order',
        ),
        migrations.AddField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(default=1, verbose_name='порядок'),
            preserve_default=False,
        ),
    ]
