# Generated by Django 5.2.17 on 2026-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.RemoveField(
            model_name='place',
            name='order',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(db_index=True, verbose_name='порядок'),
        ),
    ]
